# Generated by Django 3.2.14 on 2022-07-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ability_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='base_experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.CharField(help_text='Type of pokemon', max_length=250),
        ),
    ]
