# Generated by Django 3.2.14 on 2022-07-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220721_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pokemon'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ability'),
        ),
    ]
